import { STANDARD_BUCKET_COLORS, type RangeBucket } from "@/app/components/tools/body-weight/shared/ui";

export const IDEAL_WEIGHT_PERCENT_RANGES: RangeBucket[] = [
  {
    key: "well-below",
    label: "Well Below Target",
    min: 0,
    max: 90,
    rowClass: STANDARD_BUCKET_COLORS.blue.row,
    color: STANDARD_BUCKET_COLORS.blue.dot,
    note: "Current weight is far below reference target. Clinical context matters for interpretation.",
    shortLabel: "<90%",
  },
  {
    key: "near-target-low",
    label: "Near Target (Low)",
    min: 90,
    max: 100,
    rowClass: STANDARD_BUCKET_COLORS.green.row,
    color: STANDARD_BUCKET_COLORS.green.dot,
    note: "Near the selected target and below or at reference value.",
    shortLabel: "90-100%",
  },
  {
    key: "near-target-high",
    label: "Near Target (High)",
    min: 100,
    max: 110,
    rowClass: STANDARD_BUCKET_COLORS.yellow.row,
    color: STANDARD_BUCKET_COLORS.yellow.dot,
    note: "Close to selected target range and often manageable with minor adjustments.",
    shortLabel: "100-110%",
  },
  {
    key: "above-target",
    label: "Above Target",
    min: 110,
    max: 120,
    rowClass: STANDARD_BUCKET_COLORS.orange.row,
    color: STANDARD_BUCKET_COLORS.orange.dot,
    note: "Above reference target. Use trend-based planning rather than aggressive short-term cuts.",
    shortLabel: "110-120%",
  },
  {
    key: "high",
    label: "High",
    min: 120,
    max: 130,
    rowClass: STANDARD_BUCKET_COLORS.red.row,
    color: STANDARD_BUCKET_COLORS.red.dot,
    note: "Substantially above target reference. Structured deficit planning can help.",
    shortLabel: "120-130%",
  },
  {
    key: "very-high",
    label: "Very High",
    min: 130,
    max: Infinity,
    rowClass: STANDARD_BUCKET_COLORS.purple.row,
    color: STANDARD_BUCKET_COLORS.purple.dot,
    note: "Well above reference target. Consider medical guidance for individualized planning.",
    shortLabel: "130%+",
  },
];
