import { STANDARD_BUCKET_COLORS, type RangeBucket } from "@/app/components/tools/body-weight/shared/ui";

export const WEIGHT_LOSS_PERCENTAGE_RANGES: RangeBucket[] = [
  {
    key: "gain",
    label: "Weight Gain",
    min: -10,
    max: 0,
    rowClass: STANDARD_BUCKET_COLORS.red.row,
    color: STANDARD_BUCKET_COLORS.red.dot,
    note: "Current weight is above your starting point. Check weekly trends before making major adjustments.",
    shortLabel: "Gain",
  },
  {
    key: "modest",
    label: "Modest",
    min: 0,
    max: 5,
    rowClass: STANDARD_BUCKET_COLORS.orange.row,
    color: STANDARD_BUCKET_COLORS.orange.dot,
    note: "Early progress range. Useful for building consistency while preserving training performance.",
    shortLabel: "0-5%",
  },
  {
    key: "clinically-meaningful",
    label: "Clinically Meaningful",
    min: 5,
    max: 10,
    rowClass: STANDARD_BUCKET_COLORS.yellow.row,
    color: STANDARD_BUCKET_COLORS.yellow.dot,
    note: "A 5-10% reduction is commonly associated with improved cardiometabolic markers.",
    shortLabel: "5-10%",
  },
  {
    key: "significant",
    label: "Significant",
    min: 10,
    max: 15,
    rowClass: STANDARD_BUCKET_COLORS.green.row,
    color: STANDARD_BUCKET_COLORS.green.dot,
    note: "Substantial progress. Maintain protein, sleep, and resistance training to reduce lean-mass loss.",
    shortLabel: "10-15%",
  },
  {
    key: "high",
    label: "High",
    min: 15,
    max: 20,
    rowClass: STANDARD_BUCKET_COLORS.teal.row,
    color: STANDARD_BUCKET_COLORS.teal.dot,
    note: "Higher total loss. Recovery and adherence become more important as adaptation increases.",
    shortLabel: "15-20%",
  },
  {
    key: "very-high",
    label: "Very High",
    min: 20,
    max: 30,
    rowClass: STANDARD_BUCKET_COLORS.blue.row,
    color: STANDARD_BUCKET_COLORS.blue.dot,
    note: "Large reduction from baseline. Consider periodic maintenance blocks for long-term sustainability.",
    shortLabel: "20-30%",
  },
  {
    key: "extreme",
    label: "Extreme",
    min: 30,
    max: Infinity,
    rowClass: STANDARD_BUCKET_COLORS.purple.row,
    color: STANDARD_BUCKET_COLORS.purple.dot,
    note: "Very high total loss. Clinical supervision is recommended, especially with medications or chronic conditions.",
    shortLabel: "30%+",
  },
];
