import { STANDARD_BUCKET_COLORS, type RangeBucket } from "@/app/components/tools/body-weight/shared/ui";

export const TDEE_ACTIVITY_FACTOR_RANGES: RangeBucket[] = [
  {
    key: "very-sedentary",
    label: "Very Sedentary",
    min: 1.0,
    max: 1.2,
    rowClass: STANDARD_BUCKET_COLORS.blue.row,
    color: STANDARD_BUCKET_COLORS.blue.dot,
    note: "Little planned movement. Most of the day is seated.",
    shortLabel: "Very Sed",
  },
  {
    key: "sedentary",
    label: "Sedentary",
    min: 1.2,
    max: 1.375,
    rowClass: STANDARD_BUCKET_COLORS.green.row,
    color: STANDARD_BUCKET_COLORS.green.dot,
    note: "Minimal structured training. Low daily step count.",
    shortLabel: "Sed",
  },
  {
    key: "light",
    label: "Lightly Active",
    min: 1.375,
    max: 1.55,
    rowClass: STANDARD_BUCKET_COLORS.yellow.row,
    color: STANDARD_BUCKET_COLORS.yellow.dot,
    note: "Light training or walking on most days.",
    shortLabel: "Light",
  },
  {
    key: "moderate",
    label: "Moderately Active",
    min: 1.55,
    max: 1.725,
    rowClass: STANDARD_BUCKET_COLORS.orange.row,
    color: STANDARD_BUCKET_COLORS.orange.dot,
    note: "Regular moderate-intensity exercise during the week.",
    shortLabel: "Mod",
  },
  {
    key: "very",
    label: "Very Active",
    min: 1.725,
    max: 1.9,
    rowClass: STANDARD_BUCKET_COLORS.red.row,
    color: STANDARD_BUCKET_COLORS.red.dot,
    note: "Hard training most days or physically active work.",
    shortLabel: "Very",
  },
  {
    key: "extra",
    label: "Extra Active",
    min: 1.9,
    max: Infinity,
    rowClass: STANDARD_BUCKET_COLORS.purple.row,
    color: STANDARD_BUCKET_COLORS.purple.dot,
    note: "Very high training volume and/or manual labor demands.",
    shortLabel: "Extra",
  },
];
