import { STANDARD_BUCKET_COLORS, type RangeBucket } from "@/app/components/tools/body-weight/shared/ui";

export const BROCA_PERCENT_RANGES: RangeBucket[] = [
  {
    key: "well-below",
    label: "Well Below Broca",
    min: 0,
    max: 90,
    rowClass: STANDARD_BUCKET_COLORS.blue.row,
    color: STANDARD_BUCKET_COLORS.blue.dot,
    note: "Current weight is far below the Broca reference.",
    shortLabel: "<90%",
  },
  {
    key: "near-target-low",
    label: "Near Broca (Low)",
    min: 90,
    max: 100,
    rowClass: STANDARD_BUCKET_COLORS.green.row,
    color: STANDARD_BUCKET_COLORS.green.dot,
    note: "Near the Broca reference and below or at target.",
    shortLabel: "90-100%",
  },
  {
    key: "near-target-high",
    label: "Near Broca (High)",
    min: 100,
    max: 110,
    rowClass: STANDARD_BUCKET_COLORS.yellow.row,
    color: STANDARD_BUCKET_COLORS.yellow.dot,
    note: "Slightly above Broca reference range.",
    shortLabel: "100-110%",
  },
  {
    key: "above-target",
    label: "Above Broca",
    min: 110,
    max: 120,
    rowClass: STANDARD_BUCKET_COLORS.orange.row,
    color: STANDARD_BUCKET_COLORS.orange.dot,
    note: "Above Broca reference with moderate divergence.",
    shortLabel: "110-120%",
  },
  {
    key: "high",
    label: "High Above Broca",
    min: 120,
    max: 130,
    rowClass: STANDARD_BUCKET_COLORS.red.row,
    color: STANDARD_BUCKET_COLORS.red.dot,
    note: "Substantially above Broca reference.",
    shortLabel: "120-130%",
  },
  {
    key: "very-high",
    label: "Very High Above Broca",
    min: 130,
    max: Infinity,
    rowClass: STANDARD_BUCKET_COLORS.purple.row,
    color: STANDARD_BUCKET_COLORS.purple.dot,
    note: "Large divergence from Broca target; use with modern tools for context.",
    shortLabel: "130%+",
  },
];
