import { STANDARD_BUCKET_COLORS, type RangeBucket } from "@/app/components/tools/body-weight/shared/ui";

export const CALORIES_BURNED_RANGES: RangeBucket[] = [
  {
    key: "low",
    label: "Low Burn",
    min: 0,
    max: 150,
    rowClass: STANDARD_BUCKET_COLORS.yellow.row,
    color: STANDARD_BUCKET_COLORS.yellow.dot,
    note: "Short or lower-intensity sessions with smaller calorie output.",
    shortLabel: "<150",
  },
  {
    key: "light",
    label: "Light Burn",
    min: 150,
    max: 300,
    rowClass: STANDARD_BUCKET_COLORS.green.row,
    color: STANDARD_BUCKET_COLORS.green.dot,
    note: "Typical output for moderate-duration light to moderate sessions.",
    shortLabel: "150-299",
  },
  {
    key: "moderate",
    label: "Moderate Burn",
    min: 300,
    max: 500,
    rowClass: STANDARD_BUCKET_COLORS.teal.row,
    color: STANDARD_BUCKET_COLORS.teal.dot,
    note: "Solid session burn from longer duration or higher effort.",
    shortLabel: "300-499",
  },
  {
    key: "high",
    label: "High Burn",
    min: 500,
    max: 800,
    rowClass: STANDARD_BUCKET_COLORS.blue.row,
    color: STANDARD_BUCKET_COLORS.blue.dot,
    note: "High-output training session with substantial energy expenditure.",
    shortLabel: "500-799",
  },
  {
    key: "very-high",
    label: "Very High Burn",
    min: 800,
    max: Infinity,
    rowClass: STANDARD_BUCKET_COLORS.purple.row,
    color: STANDARD_BUCKET_COLORS.purple.dot,
    note: "Very demanding sessions; verify recovery, fueling, and consistency.",
    shortLabel: "800+",
  },
];
