import { STANDARD_BUCKET_COLORS, type RangeBucket } from "./ui";

export const WEIGHT_LOSS_PACE_RANGES: RangeBucket[] = [
  {
    key: "gain",
    label: "Weight Gain",
    min: -1,
    max: 0,
    rowClass: STANDARD_BUCKET_COLORS.red.row,
    color: STANDARD_BUCKET_COLORS.red.dot,
    note: "Average energy intake appears above expenditure in this setup.",
    shortLabel: "Gain",
  },
  {
    key: "very-slow",
    label: "Very Slow",
    min: 0,
    max: 0.25,
    rowClass: STANDARD_BUCKET_COLORS.orange.row,
    color: STANDARD_BUCKET_COLORS.orange.dot,
    note: "Low weekly rate. Useful for maintenance-adjacent phases or conservative starts.",
    shortLabel: "0-0.25%",
  },
  {
    key: "steady",
    label: "Steady",
    min: 0.25,
    max: 0.75,
    rowClass: STANDARD_BUCKET_COLORS.yellow.row,
    color: STANDARD_BUCKET_COLORS.yellow.dot,
    note: "Typical sustainable pace for many adults.",
    shortLabel: "0.25-0.75%",
  },
  {
    key: "brisk",
    label: "Brisk",
    min: 0.75,
    max: 1,
    rowClass: STANDARD_BUCKET_COLORS.green.row,
    color: STANDARD_BUCKET_COLORS.green.dot,
    note: "Faster but often manageable with adequate protein and recovery.",
    shortLabel: "0.75-1%",
  },
  {
    key: "aggressive",
    label: "Aggressive",
    min: 1,
    max: 1.5,
    rowClass: STANDARD_BUCKET_COLORS.teal.row,
    color: STANDARD_BUCKET_COLORS.teal.dot,
    note: "Aggressive pace. Monitor performance, hunger, and sleep quality closely.",
    shortLabel: "1-1.5%",
  },
  {
    key: "very-aggressive",
    label: "Very Aggressive",
    min: 1.5,
    max: 2,
    rowClass: STANDARD_BUCKET_COLORS.blue.row,
    color: STANDARD_BUCKET_COLORS.blue.dot,
    note: "High weekly rate with increased lean-mass retention risk.",
    shortLabel: "1.5-2%",
  },
  {
    key: "extreme",
    label: "Extreme",
    min: 2,
    max: Infinity,
    rowClass: STANDARD_BUCKET_COLORS.purple.row,
    color: STANDARD_BUCKET_COLORS.purple.dot,
    note: "Very high projected pace. Medical supervision is recommended.",
    shortLabel: ">2%",
  },
];
