import { STANDARD_BUCKET_COLORS, type RangeBucket } from "@/app/components/tools/body-weight/shared/ui";

export const OVERWEIGHT_BMI_RANGES: RangeBucket[] = [
  {
    key: "underweight",
    label: "Underweight",
    min: 0,
    max: 18.5,
    rowClass: STANDARD_BUCKET_COLORS.blue.row,
    color: STANDARD_BUCKET_COLORS.blue.dot,
    note: "Below standard BMI range for adults. Clinical context matters for interpretation.",
    shortLabel: "Under",
  },
  {
    key: "healthy",
    label: "Healthy Range",
    min: 18.5,
    max: 25,
    rowClass: STANDARD_BUCKET_COLORS.green.row,
    color: STANDARD_BUCKET_COLORS.green.dot,
    note: "Standard healthy BMI range for adults (18.5-24.9).",
    shortLabel: "Healthy",
  },
  {
    key: "overweight",
    label: "Overweight",
    min: 25,
    max: 30,
    rowClass: STANDARD_BUCKET_COLORS.yellow.row,
    color: STANDARD_BUCKET_COLORS.yellow.dot,
    note: "Above healthy BMI range. Additional risk depends on waist size and other factors.",
    shortLabel: "Over",
  },
  {
    key: "obesity-class-1",
    label: "Obesity Class I",
    min: 30,
    max: 35,
    rowClass: STANDARD_BUCKET_COLORS.orange.row,
    color: STANDARD_BUCKET_COLORS.orange.dot,
    note: "Higher BMI category with increased cardiometabolic risk in most populations.",
    shortLabel: "Class I",
  },
  {
    key: "obesity-class-2",
    label: "Obesity Class II",
    min: 35,
    max: 40,
    rowClass: STANDARD_BUCKET_COLORS.red.row,
    color: STANDARD_BUCKET_COLORS.red.dot,
    note: "Substantially elevated BMI category. Clinical management is often recommended.",
    shortLabel: "Class II",
  },
  {
    key: "obesity-class-3",
    label: "Obesity Class III",
    min: 40,
    max: Infinity,
    rowClass: STANDARD_BUCKET_COLORS.purple.row,
    color: STANDARD_BUCKET_COLORS.purple.dot,
    note: "Highest standard BMI category. Medical follow-up is generally advised.",
    shortLabel: "Class III",
  },
];
