import { STANDARD_BUCKET_COLORS, type RangeBucket } from "@/app/components/tools/body-weight/shared/ui";

export const ADJUSTED_BODY_WEIGHT_PERCENT_RANGES: RangeBucket[] = [
  {
    key: "below-ibw",
    label: "Below IBW",
    min: 0,
    max: 100,
    rowClass: STANDARD_BUCKET_COLORS.blue.row,
    color: STANDARD_BUCKET_COLORS.blue.dot,
    note: "Actual body weight is below ideal body weight reference.",
    shortLabel: "<100%",
  },
  {
    key: "near-ibw",
    label: "Near IBW",
    min: 100,
    max: 120,
    rowClass: STANDARD_BUCKET_COLORS.green.row,
    color: STANDARD_BUCKET_COLORS.green.dot,
    note: "Actual body weight is within roughly 100-120% of IBW.",
    shortLabel: "100-120%",
  },
  {
    key: "adjbw-range",
    label: "AdjBW Commonly Used",
    min: 120,
    max: 140,
    rowClass: STANDARD_BUCKET_COLORS.yellow.row,
    color: STANDARD_BUCKET_COLORS.yellow.dot,
    note: "In many dosing protocols, adjusted body weight is considered from >=120% of IBW.",
    shortLabel: "120-140%",
  },
  {
    key: "high-above-ibw",
    label: "High Above IBW",
    min: 140,
    max: 160,
    rowClass: STANDARD_BUCKET_COLORS.orange.row,
    color: STANDARD_BUCKET_COLORS.orange.dot,
    note: "Substantially above IBW reference. Dose strategy should follow medication-specific guidance.",
    shortLabel: "140-160%",
  },
  {
    key: "very-high-above-ibw",
    label: "Very High Above IBW",
    min: 160,
    max: Infinity,
    rowClass: STANDARD_BUCKET_COLORS.red.row,
    color: STANDARD_BUCKET_COLORS.red.dot,
    note: "Large divergence from IBW reference. Use clinician or protocol-driven dosing pathways.",
    shortLabel: "160%+",
  },
];
