import { STANDARD_BUCKET_COLORS, type RangeBucket } from "@/app/components/tools/body-weight/shared/ui";

export const STEPS_ACTIVITY_RANGES: RangeBucket[] = [
  {
    key: "very-low",
    label: "Very Low",
    min: 0,
    max: 5000,
    rowClass: STANDARD_BUCKET_COLORS.red.row,
    color: STANDARD_BUCKET_COLORS.red.dot,
    note: "Daily movement is usually low and mostly sedentary.",
    shortLabel: "<5k",
  },
  {
    key: "low-active",
    label: "Low Active",
    min: 5000,
    max: 7500,
    rowClass: STANDARD_BUCKET_COLORS.orange.row,
    color: STANDARD_BUCKET_COLORS.orange.dot,
    note: "Some walking volume, but still below common daily activity targets.",
    shortLabel: "5-7.5k",
  },
  {
    key: "somewhat-active",
    label: "Somewhat Active",
    min: 7500,
    max: 10000,
    rowClass: STANDARD_BUCKET_COLORS.yellow.row,
    color: STANDARD_BUCKET_COLORS.yellow.dot,
    note: "Moderate step volume that often supports baseline weight maintenance.",
    shortLabel: "7.5-10k",
  },
  {
    key: "active",
    label: "Active",
    min: 10000,
    max: 12500,
    rowClass: STANDARD_BUCKET_COLORS.green.row,
    color: STANDARD_BUCKET_COLORS.green.dot,
    note: "Solid daily step volume for general activity and energy expenditure.",
    shortLabel: "10-12.5k",
  },
  {
    key: "high-active",
    label: "High Active",
    min: 12500,
    max: 15000,
    rowClass: STANDARD_BUCKET_COLORS.teal.row,
    color: STANDARD_BUCKET_COLORS.teal.dot,
    note: "High daily movement that usually reflects intentional walking volume.",
    shortLabel: "12.5-15k",
  },
  {
    key: "very-high",
    label: "Very High",
    min: 15000,
    max: Infinity,
    rowClass: STANDARD_BUCKET_COLORS.blue.row,
    color: STANDARD_BUCKET_COLORS.blue.dot,
    note: "Very high step totals with substantial daily energy expenditure from walking.",
    shortLabel: "15k+",
  },
];

