import { STANDARD_BUCKET_COLORS, type RangeBucket } from "@/app/components/tools/body-weight/shared/ui";

export const BMR_PER_KG_RANGES: RangeBucket[] = [
  {
    key: "very-low",
    label: "Very Low",
    min: 0,
    max: 18,
    rowClass: STANDARD_BUCKET_COLORS.blue.row,
    color: STANDARD_BUCKET_COLORS.blue.dot,
    note: "Lower resting-energy output relative to body mass.",
    shortLabel: "<18",
  },
  {
    key: "low-moderate",
    label: "Low to Moderate",
    min: 18,
    max: 22,
    rowClass: STANDARD_BUCKET_COLORS.green.row,
    color: STANDARD_BUCKET_COLORS.green.dot,
    note: "Common lower-middle resting-energy band.",
    shortLabel: "18-22",
  },
  {
    key: "typical",
    label: "Typical",
    min: 22,
    max: 26,
    rowClass: STANDARD_BUCKET_COLORS.yellow.row,
    color: STANDARD_BUCKET_COLORS.yellow.dot,
    note: "Typical resting-energy output per kg for many adults.",
    shortLabel: "22-26",
  },
  {
    key: "elevated",
    label: "Elevated",
    min: 26,
    max: 30,
    rowClass: STANDARD_BUCKET_COLORS.orange.row,
    color: STANDARD_BUCKET_COLORS.orange.dot,
    note: "Higher resting-energy output relative to body mass.",
    shortLabel: "26-30",
  },
  {
    key: "high",
    label: "High",
    min: 30,
    max: Infinity,
    rowClass: STANDARD_BUCKET_COLORS.red.row,
    color: STANDARD_BUCKET_COLORS.red.dot,
    note: "Very high resting-energy output per kg body mass.",
    shortLabel: "30+",
  },
];
