import { STANDARD_BUCKET_COLORS, type RangeBucket } from "@/app/components/tools/body-weight/shared/ui";

export const CALORIE_GOAL_ADJUSTMENT_RANGES: RangeBucket[] = [
  {
    key: "aggressive-deficit",
    label: "Aggressive Deficit",
    min: -100,
    max: -20,
    rowClass: STANDARD_BUCKET_COLORS.red.row,
    color: STANDARD_BUCKET_COLORS.red.dot,
    note: "Large intake reduction. Higher adherence and recovery risk for most people.",
    shortLabel: "<-20%",
  },
  {
    key: "deficit",
    label: "Deficit",
    min: -20,
    max: -12,
    rowClass: STANDARD_BUCKET_COLORS.orange.row,
    color: STANDARD_BUCKET_COLORS.orange.dot,
    note: "Typical fat-loss range. Works best with training, protein, and sleep consistency.",
    shortLabel: "-20 to -12%",
  },
  {
    key: "mild-deficit",
    label: "Mild Deficit",
    min: -12,
    max: -5,
    rowClass: STANDARD_BUCKET_COLORS.yellow.row,
    color: STANDARD_BUCKET_COLORS.yellow.dot,
    note: "Slower pace, often easier to sustain while preserving performance.",
    shortLabel: "-12 to -5%",
  },
  {
    key: "maintenance",
    label: "Maintenance",
    min: -5,
    max: 5,
    rowClass: STANDARD_BUCKET_COLORS.green.row,
    color: STANDARD_BUCKET_COLORS.green.dot,
    note: "Target zone for weight maintenance after normal week-to-week variance.",
    shortLabel: "-5 to +5%",
  },
  {
    key: "mild-surplus",
    label: "Mild Surplus",
    min: 5,
    max: 12,
    rowClass: STANDARD_BUCKET_COLORS.blue.row,
    color: STANDARD_BUCKET_COLORS.blue.dot,
    note: "Lean-gain style surplus commonly used for slower mass-gain phases.",
    shortLabel: "+5 to +12%",
  },
  {
    key: "surplus",
    label: "Surplus",
    min: 12,
    max: 20,
    rowClass: STANDARD_BUCKET_COLORS.purple.row,
    color: STANDARD_BUCKET_COLORS.purple.dot,
    note: "Faster gain phase with higher probability of fat gain alongside weight gain.",
    shortLabel: "+12 to +20%",
  },
  {
    key: "high-surplus",
    label: "High Surplus",
    min: 20,
    max: Infinity,
    rowClass: STANDARD_BUCKET_COLORS.red.row,
    color: STANDARD_BUCKET_COLORS.red.dot,
    note: "Very high intake above maintenance. Usually unnecessary for most goals.",
    shortLabel: ">+20%",
  },
];
