import { STANDARD_BUCKET_COLORS, type RangeBucket } from "@/app/components/tools/body-weight/shared/ui";

export const MACRO_CALORIE_ADJUSTMENT_RANGES: RangeBucket[] = [
  {
    key: "aggressive-cut",
    label: "Aggressive Cut",
    min: -50,
    max: -25,
    rowClass: STANDARD_BUCKET_COLORS.red.row,
    color: STANDARD_BUCKET_COLORS.red.dot,
    note: "Large deficit. Can be effective short-term but harder to sustain.",
    shortLabel: "Agg Cut",
  },
  {
    key: "moderate-cut",
    label: "Moderate Cut",
    min: -25,
    max: -12,
    rowClass: STANDARD_BUCKET_COLORS.orange.row,
    color: STANDARD_BUCKET_COLORS.orange.dot,
    note: "Common fat-loss range with reasonable appetite and recovery tradeoffs.",
    shortLabel: "Mod Cut",
  },
  {
    key: "mild-cut",
    label: "Mild Cut",
    min: -12,
    max: -3,
    rowClass: STANDARD_BUCKET_COLORS.yellow.row,
    color: STANDARD_BUCKET_COLORS.yellow.dot,
    note: "Conservative deficit focused on consistency and lean-mass retention.",
    shortLabel: "Mild Cut",
  },
  {
    key: "maintenance",
    label: "Maintenance",
    min: -3,
    max: 3,
    rowClass: STANDARD_BUCKET_COLORS.green.row,
    color: STANDARD_BUCKET_COLORS.green.dot,
    note: "Near-maintenance intake where body weight may stay roughly stable.",
    shortLabel: "Maintain",
  },
  {
    key: "lean-gain",
    label: "Lean Gain",
    min: 3,
    max: 12,
    rowClass: STANDARD_BUCKET_COLORS.teal.row,
    color: STANDARD_BUCKET_COLORS.teal.dot,
    note: "Small surplus often used for gradual muscle gain phases.",
    shortLabel: "Lean Gain",
  },
  {
    key: "bulk",
    label: "Bulk",
    min: 12,
    max: 25,
    rowClass: STANDARD_BUCKET_COLORS.blue.row,
    color: STANDARD_BUCKET_COLORS.blue.dot,
    note: "Larger surplus with faster scale-weight gain and higher fat-gain risk.",
    shortLabel: "Bulk",
  },
  {
    key: "aggressive-surplus",
    label: "Aggressive Surplus",
    min: 25,
    max: Infinity,
    rowClass: STANDARD_BUCKET_COLORS.purple.row,
    color: STANDARD_BUCKET_COLORS.purple.dot,
    note: "Very large surplus. Useful rarely; monitor body-composition changes closely.",
    shortLabel: "Agg Surp",
  },
];

